### ISSUE TITLE
auth: Support for credentials (using ~/.kube/config)

### ISSUE THREAD

**Issue by brianmartin** [mkokho/kubemrr#5]
This is a requirement for using `kubemrr` with deployments on GKE or AWS (e.g. using [kube-aws]( https://github.com/coreos/kube-aws)).

**Comment by mkokho** [comment]
could you give an example configuration? I'd like to know more of the credentials you need.

We use `client-certificate` and `client-key`, as in example below
```
kind: Config
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/x/.kube/prod-ca.pem
    server: https://kube-prod.example.com:8443
  name: prod
contexts:
- context:
    cluster: prod
    user: all
  name: prod
users:
- name: all
  user:
    client-certificate: /home/x/.vpn/x.pem
    client-key: /home/x/.vpn/x-key.pem
```
